spring.application.name=Smart Trip Planner2
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080


# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=url
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# GOOGLE OAUTH2 CONFIGURATION
# ===============================
spring.security.oauth2.client.registration.google.client-id=client-id
spring.security.oauth2.client.registration.google.client-secret=client-secret
spring.security.oauth2.client.registration.google.scope=email,profile


# ===============================
# GITHUB OAUTH2 CONFIGURATION
# ===============================
spring.security.oauth2.client.registration.github.client-id=client id
spring.security.oauth2.client.registration.github.client-secret=client secret

spring.security.oauth2.client.registration.github.scope=user:email,read:user


# ===============================
# JWT CONFIGURATION
# ===============================
app.jwt.secret=your-256-bit-secret-key-replace-in-production-min-32-chars

# 15 minutes
app.jwt.expiration-ms=9000000

# 7 days
app.jwt.refresh-expiration-ms=604800000


# Razorpay Configuration


razorpay.key.id=rzp_test
razorpay.key.secret=6UN7*********
razorpay.currency=INR